groups:
  - name: service_metrics
    interval: 30s
    rules:
      - record: service:http_request_rate_5m
        expr: rate(http_requests_total[5m])
      
      - record: service:http_error_rate_5m
        expr: rate(http_requests_total{status=~"5.."}[5m])
      
      - record: service:http_p95_latency_5m
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))
      
      - record: service:http_p99_latency_5m
        expr: histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))

  - name: business_metrics
    interval: 1m
    rules:
      - record: business:orders_created_rate_5m
        expr: rate(orders_created_total[5m])
      
      - record: business:revenue_rate_5m
        expr: rate(order_value_total[5m])
      
      - record: business:cart_abandonment_rate_5m
        expr: |
          rate(carts_created_total[5m]) - rate(orders_created_total[5m])
          / rate(carts_created_total[5m])
      
      - record: business:payment_success_rate_5m
        expr: |
          rate(payments_processed_total{status="success"}[5m])
          / rate(payments_processed_total[5m])

  - name: infrastructure_metrics
    interval: 30s
    rules:
      - record: instance:cpu_utilization
        expr: |
          100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)
      
      - record: instance:memory_utilization
        expr: |
          (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100
      
      - record: container:cpu_usage_percentage
        expr: |
          rate(container_cpu_usage_seconds_total[5m]) * 100
      
      - record: container:memory_usage_percentage
        expr: |
          (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100

  - name: alerts
    interval: 30s
    rules:
      - alert: HighErrorRate
        expr: service:http_error_rate_5m > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "{{ $labels.job }} has error rate of {{ $value }}"
      
      - alert: HighLatency
        expr: service:http_p95_latency_5m > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "{{ $labels.job }} has p95 latency of {{ $value }}s"
      
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service is down"
          description: "{{ $labels.job }} is down"
      
      - alert: HighMemoryUsage
        expr: instance:memory_utilization > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage"
          description: "{{ $labels.instance }} memory usage is {{ $value }}%"
      
      - alert: HighCPUUsage
        expr: instance:cpu_utilization > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "{{ $labels.instance }} CPU usage is {{ $value }}%"
      
      - alert: PaymentFailureRate
        expr: business:payment_success_rate_5m < 0.95
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High payment failure rate"
          description: "Payment success rate is {{ $value }}"